name: Build

on:
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ mainline ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make release plugins.tgz
